-- ROLE 데이터 삽입
INSERT INTO ROLE (ROLE_ID, NAME) VALUES ('ADMIN', '관리자');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES ('USER', '사용자');

-- USERS 데이터 삽입
INSERT INTO "USER" (ID, ROLE_ID, PROVIDER, PROVIDER_ID, EMAIL, NICKNAME, BIRTHDAY, GENDER)
VALUES ('NAVER_12345', 'ADMIN', 'NAVER', '12345', 'admin@example.com', 'AdminUser', '1985-05-15', 'F');
INSERT INTO "USER" (ID, ROLE_ID, PROVIDER, PROVIDER_ID, EMAIL, NICKNAME, BIRTHDAY, GENDER)
VALUES ('KAKAO_12345', 'USER', 'KAKAO', '12345',  'user1@example.com', 'UserOne', '1990-01-01', 'M');
INSERT INTO "USER" (ID, ROLE_ID, PROVIDER, PROVIDER_ID, EMAIL, NICKNAME, BIRTHDAY, GENDER)
VALUES ('GOOGLE_12345', 'USER', 'GOOGLE', '12345', 'user2@example.com', 'UserTwo', '1992-07-21', 'M');

-- CATEGORY 데이터 삽입
INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (1, '자유게시판');

-- POST 데이터 삽입
INSERT INTO POST (POST_ID, CATEGORY_ID, TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (1, 1, 'Welcome to the Forum', 'This is the first post.', 'KAKAO_12345', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO POST (POST_ID, CATEGORY_ID, TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (2, 1, 'Update Notice', 'We have updated our policies.', 'NAVER_67890', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO POST (POST_ID, CATEGORY_ID, TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (3, 1, 'Technical Tips', 'Here are some tips for beginners.', 'GOOGLE_12345', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- COMMENT 데이터 삽입
INSERT INTO COMMENT (COMMENT_ID, POST_ID, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (1, 1, 'Great post!', 'KAKAO_12345', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMMENT (COMMENT_ID, POST_ID, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (2, 2, 'Thanks for the update!', 'NAVER_67890', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO COMMENT (COMMENT_ID, POST_ID, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT)
VALUES (3, 3, 'Helpful tips, thank you!', 'GOOGLE_12345', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- PERMISSION 데이터 삽입
INSERT INTO PERMISSION (ROLE_ID, EDIT_OWN_POST, EDIT_ALL_POST, EDIT_OWN_COMMENT, EDIT_ALL_COMMENT)
VALUES ('ADMIN', 1, 1, 1, 1);
INSERT INTO PERMISSION (ROLE_ID, EDIT_OWN_POST, EDIT_ALL_POST, EDIT_OWN_COMMENT, EDIT_ALL_COMMENT)
VALUES ('USER', 1, 0, 1, 0);
