CREATE TABLE IF NOT EXISTS "USER" (
                      USER_ID VARCHAR NOT NULL COMMENT 'PROVIDER와 PROVIDER_ID 조합으로 자동 생성',
                      ROLE_ID VARCHAR NOT NULL,
                      PROVIDER_ID VARCHAR NOT NULL COMMENT '카카오,네이버,구글에서 제공받는 아이디',
                      PROVIDER VARCHAR NOT NULL,
                      EMAIL VARCHAR NULL,
                      NICKNAME VARCHAR(100) NULL,
                      BIRTHDAY DATE NULL,
                      GENDER CHAR NULL,
                      PET_OWN CHAR NULL,
                      PROFILE_IMG_URL VARCHAR NULL,
                      INTRODUCTION VARCHAR NULL,
                      PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS ROLE (
                      ROLE_ID VARCHAR NOT NULL,
                      NAME VARCHAR NULL,
                      PRIMARY KEY (ROLE_ID)
);

-- CREATE TABLE POST (
--                       POST_ID INT AUTO_INCREMENT NOT NULL COMMENT 'AUTO INCREMENT',
--                       CATEGORY_ID VARCHAR NOT NULL,
--                       USER_ID VARCHAR NOT NULL COMMENT '작성자',
--                       TITLE VARCHAR NULL,
--                       CONTENT TEXT NULL,
--                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                       PRIMARY KEY (POST_ID)
-- );
--
-- CREATE TABLE CATEGORY (
--                           CATEGORY_ID VARCHAR NOT NULL COMMENT 'AUTO INCREMENT',
--                           NAME VARCHAR NULL,
--                           PRIMARY KEY (CATEGORY_ID)
-- );
--
-- CREATE TABLE COMMENT (
--                          COMMENT_ID INT AUTO_INCREMENT NOT NULL COMMENT 'AUTO INCREMENT',
--                          POST_ID INT NOT NULL,
--                          USER_ID VARCHAR NOT NULL COMMENT '작성자',
--                          CONTENT TEXT NULL,
--                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                          PRIMARY KEY (COMMENT_ID)
-- );

CREATE TABLE IF NOT EXISTS PERMISSION (
                            ROLE_ID VARCHAR NOT NULL,
                            EDIT_OWN_POST BOOLEAN NULL,
                            EDIT_ALL_POST BOOLEAN NULL,
                            EDIT_OWN_COMMENT BOOLEAN NULL,
                            EDIT_ALL_COMMENT BOOLEAN NULL,
                            PRIMARY KEY (ROLE_ID)
);

CREATE TABLE IF NOT EXISTS PET (
                     PET_ID INT AUTO_INCREMENT NOT NULL COMMENT 'AUTO INCREMENT',
                     USER_ID VARCHAR NOT NULL,
                     NAME VARCHAR NULL,
                     BIRTHDAY DATE NULL,
                     GENDER CHAR NULL,
                     NEUTERING CHAR NULL,
                     PRIMARY KEY (PET_ID)
);

-- Foreign Key Constraints
-- ALTER TABLE "USER" ADD CONSTRAINT FK_ROLE_TO_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);

-- ALTER TABLE POST ADD CONSTRAINT FK_CATEGORY_TO_POST FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);
-- ALTER TABLE POST ADD CONSTRAINT FK_USER_TO_POST FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);
--
-- ALTER TABLE COMMENT ADD CONSTRAINT FK_POST_TO_COMMENT FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID);
-- ALTER TABLE COMMENT ADD CONSTRAINT FK_USER_TO_COMMENT FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);

-- ALTER TABLE PERMISSION ADD CONSTRAINT FK_ROLE_TO_PERMISSION FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);

-- ALTER TABLE PET ADD CONSTRAINT FK_USER_TO_PET FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);